import type {Metadata} from 'next';
import localFont from 'next/font/local';
import '@/styles/globals.css';
import {ReactNode} from 'react';

import Providers from '@/components/Providers';
import Header from '@/components/Header';

const geistSans = localFont({
   src: './fonts/GeistVF.woff',
   variable: '--font-geist-sans',
   weight: '100 900',
});
const geistMono = localFont({
   src: './fonts/GeistMonoVF.woff',
   variable: '--font-geist-mono',
   weight: '100 900',
});

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${geistSans.variable} ${geistMono.variable} flex flex-col antialiased`}
         >
            <Providers>
               <Header />
               <main className={'container mx-auto flex-auto px-4'}>
                  {children}
               </main>
            </Providers>
         </body>
      </html>
   );
}
